# Generated by Django 2.1.15 on 2020-08-30 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=2500)),
                ('email', models.CharField(max_length=3000)),
                ('comment', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Latest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40000)),
                ('short_desc', models.CharField(max_length=15000)),
                ('long_dec', models.CharField(max_length=10485)),
                ('photo', models.ImageField(upload_to='burning/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=35)),
                ('msg', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_pic', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('location', models.CharField(max_length=30, null=True)),
                ('bio', models.CharField(max_length=50, null=True)),
                ('pic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=4000)),
                ('short_desc', models.CharField(max_length=15000)),
                ('long_dec', models.CharField(max_length=10485)),
                ('photo', models.ImageField(blank=True, upload_to='slideshow/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Slideshow', to='amol_blog.Slideshow'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Latest', to='amol_blog.Latest'),
        ),
    ]
